"""
Generates a downloadable "Section 25 Violation Notice" PDF from a scan record.
"""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from io import BytesIO
import datetime


def generate_notice_pdf(scan: dict) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("STATUTORY VIOLATION NOTICE", styles["Title"]))
    elements.append(Paragraph("Issued under Section 25, Legal Metrology Act, 2009", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(f"Date of Notice: {datetime.date.today().strftime('%d-%m-%Y')}", styles["Normal"]))
    elements.append(Paragraph(f"Scan Reference ID: {scan.get('id')}", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    product_name = scan.get("product_name") or "N/A"
    elements.append(Paragraph(f"<b>Product:</b> {product_name}", styles["Normal"]))
    elements.append(Spacer(1, 0.3 * cm))

    violations = scan.get("violations") or []
    if violations:
        elements.append(Paragraph("<b>Violations Identified:</b>", styles["Normal"]))
        data = [["#", "Violation"]] + [[str(i + 1), v] for i, v in enumerate(violations)]
        table = Table(data, colWidths=[1.5 * cm, 14 * cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#B00020")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        elements.append(table)
    else:
        elements.append(Paragraph("No violations identified. Product is compliant.", styles["Normal"]))

    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph(
        "This notice is system-generated by MetrologyAI based on automated geometric and "
        "regulatory verification. It is intended to assist enforcement officers and does not "
        "itself constitute final legal action.",
        styles["Italic"],
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
